version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: hub.docker.com/tutotu/centos-systemd-sshd-devcontainer
        username: totuto
        password: ymz921025
        tag: ${GITEE_BRANCH}
        dockerfile: ./Dockerfile
        isCache: false
        notify: []
strategy:
  blocking: true
permissions:
  - role: admin
    members: []
