version: '1.0'
name: pipeline-20220420
displayName: pipeline-20220420
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-f2d2a332
    displayName: 构建发布镜像
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: a06a1e30-a2e4-013a-9c3f-2e64bcce1955
        tag: ${GITEE_BRANCH}
        dockerfile: ./Dockerfile
        isCache: false
permissions:
  - role: admin
    members: []
